// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/protobuf/IndexOptions.proto

package org.apache.hadoop.hbase.index.common.protobuf;

public final class IndexOptionProtos {
  private IndexOptionProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TableIndexOptionsOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // repeated .IndexDefinition index_option = 1;
    java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition> 
        getIndexOptionList();
    org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition getIndexOption(int index);
    int getIndexOptionCount();
    java.util.List<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder> 
        getIndexOptionOrBuilderList();
    org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder getIndexOptionOrBuilder(
        int index);
  }
  public static final class TableIndexOptions extends
      com.google.protobuf.GeneratedMessage
      implements TableIndexOptionsOrBuilder {
    // Use TableIndexOptions.newBuilder() to construct.
    private TableIndexOptions(Builder builder) {
      super(builder);
    }
    private TableIndexOptions(boolean noInit) {}
    
    private static final TableIndexOptions defaultInstance;
    public static TableIndexOptions getDefaultInstance() {
      return defaultInstance;
    }
    
    public TableIndexOptions getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_TableIndexOptions_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_TableIndexOptions_fieldAccessorTable;
    }
    
    // repeated .IndexDefinition index_option = 1;
    public static final int INDEX_OPTION_FIELD_NUMBER = 1;
    private java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition> indexOption_;
    public java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition> getIndexOptionList() {
      return indexOption_;
    }
    public java.util.List<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder> 
        getIndexOptionOrBuilderList() {
      return indexOption_;
    }
    public int getIndexOptionCount() {
      return indexOption_.size();
    }
    public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition getIndexOption(int index) {
      return indexOption_.get(index);
    }
    public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder getIndexOptionOrBuilder(
        int index) {
      return indexOption_.get(index);
    }
    
    private void initFields() {
      indexOption_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < indexOption_.size(); i++) {
        output.writeMessage(1, indexOption_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (int i = 0; i < indexOption_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, indexOption_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions)) {
        return super.equals(obj);
      }
      org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions other = (org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions) obj;
      
      boolean result = true;
      result = result && getIndexOptionList()
          .equals(other.getIndexOptionList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (getIndexOptionCount() > 0) {
        hash = (37 * hash) + INDEX_OPTION_FIELD_NUMBER;
        hash = (53 * hash) + getIndexOptionList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptionsOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_TableIndexOptions_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_TableIndexOptions_fieldAccessorTable;
      }
      
      // Construct using org.apache.hadoop.hbase.index.protobuf.IndexOptionProtos.TableIndexOptions.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getIndexOptionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        if (indexOptionBuilder_ == null) {
          indexOption_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          indexOptionBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions.getDescriptor();
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions getDefaultInstanceForType() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions.getDefaultInstance();
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions build() {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions buildPartial() {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions result = new org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions(this);
        int from_bitField0_ = bitField0_;
        if (indexOptionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            indexOption_ = java.util.Collections.unmodifiableList(indexOption_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.indexOption_ = indexOption_;
        } else {
          result.indexOption_ = indexOptionBuilder_.build();
        }
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions) {
          return mergeFrom((org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions other) {
        if (other == org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions.getDefaultInstance()) return this;
        if (indexOptionBuilder_ == null) {
          if (!other.indexOption_.isEmpty()) {
            if (indexOption_.isEmpty()) {
              indexOption_ = other.indexOption_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureIndexOptionIsMutable();
              indexOption_.addAll(other.indexOption_);
            }
            onChanged();
          }
        } else {
          if (!other.indexOption_.isEmpty()) {
            if (indexOptionBuilder_.isEmpty()) {
              indexOptionBuilder_.dispose();
              indexOptionBuilder_ = null;
              indexOption_ = other.indexOption_;
              bitField0_ = (bitField0_ & ~0x00000001);
              indexOptionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getIndexOptionFieldBuilder() : null;
            } else {
              indexOptionBuilder_.addAllMessages(other.indexOption_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder subBuilder = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addIndexOption(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // repeated .IndexDefinition index_option = 1;
      private java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition> indexOption_ =
        java.util.Collections.emptyList();
      private void ensureIndexOptionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          indexOption_ = new java.util.ArrayList<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition>(indexOption_);
          bitField0_ |= 0x00000001;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder> indexOptionBuilder_;
      
      public java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition> getIndexOptionList() {
        if (indexOptionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(indexOption_);
        } else {
          return indexOptionBuilder_.getMessageList();
        }
      }
      public int getIndexOptionCount() {
        if (indexOptionBuilder_ == null) {
          return indexOption_.size();
        } else {
          return indexOptionBuilder_.getCount();
        }
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition getIndexOption(int index) {
        if (indexOptionBuilder_ == null) {
          return indexOption_.get(index);
        } else {
          return indexOptionBuilder_.getMessage(index);
        }
      }
      public Builder setIndexOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition value) {
        if (indexOptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexOptionIsMutable();
          indexOption_.set(index, value);
          onChanged();
        } else {
          indexOptionBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setIndexOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder builderForValue) {
        if (indexOptionBuilder_ == null) {
          ensureIndexOptionIsMutable();
          indexOption_.set(index, builderForValue.build());
          onChanged();
        } else {
          indexOptionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addIndexOption(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition value) {
        if (indexOptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexOptionIsMutable();
          indexOption_.add(value);
          onChanged();
        } else {
          indexOptionBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addIndexOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition value) {
        if (indexOptionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureIndexOptionIsMutable();
          indexOption_.add(index, value);
          onChanged();
        } else {
          indexOptionBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addIndexOption(
          org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder builderForValue) {
        if (indexOptionBuilder_ == null) {
          ensureIndexOptionIsMutable();
          indexOption_.add(builderForValue.build());
          onChanged();
        } else {
          indexOptionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addIndexOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder builderForValue) {
        if (indexOptionBuilder_ == null) {
          ensureIndexOptionIsMutable();
          indexOption_.add(index, builderForValue.build());
          onChanged();
        } else {
          indexOptionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllIndexOption(
          java.lang.Iterable<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition> values) {
        if (indexOptionBuilder_ == null) {
          ensureIndexOptionIsMutable();
          super.addAll(values, indexOption_);
          onChanged();
        } else {
          indexOptionBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearIndexOption() {
        if (indexOptionBuilder_ == null) {
          indexOption_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          indexOptionBuilder_.clear();
        }
        return this;
      }
      public Builder removeIndexOption(int index) {
        if (indexOptionBuilder_ == null) {
          ensureIndexOptionIsMutable();
          indexOption_.remove(index);
          onChanged();
        } else {
          indexOptionBuilder_.remove(index);
        }
        return this;
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder getIndexOptionBuilder(
          int index) {
        return getIndexOptionFieldBuilder().getBuilder(index);
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder getIndexOptionOrBuilder(
          int index) {
        if (indexOptionBuilder_ == null) {
          return indexOption_.get(index);  } else {
          return indexOptionBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder> 
           getIndexOptionOrBuilderList() {
        if (indexOptionBuilder_ != null) {
          return indexOptionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(indexOption_);
        }
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder addIndexOptionBuilder() {
        return getIndexOptionFieldBuilder().addBuilder(
            org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.getDefaultInstance());
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder addIndexOptionBuilder(
          int index) {
        return getIndexOptionFieldBuilder().addBuilder(
            index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.getDefaultInstance());
      }
      public java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder> 
           getIndexOptionBuilderList() {
        return getIndexOptionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder> 
          getIndexOptionFieldBuilder() {
        if (indexOptionBuilder_ == null) {
          indexOptionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder>(
                  indexOption_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          indexOption_ = null;
        }
        return indexOptionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:TableIndexOptions)
    }
    
    static {
      defaultInstance = new TableIndexOptions(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:TableIndexOptions)
  }
  
  public interface IndexOptionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional string name = 1;
    boolean hasName();
    String getName();
    
    // optional string value = 2;
    boolean hasValue();
    String getValue();
  }
  public static final class IndexOption extends
      com.google.protobuf.GeneratedMessage
      implements IndexOptionOrBuilder {
    // Use IndexOption.newBuilder() to construct.
    private IndexOption(Builder builder) {
      super(builder);
    }
    private IndexOption(boolean noInit) {}
    
    private static final IndexOption defaultInstance;
    public static IndexOption getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndexOption getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexOption_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexOption_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          name_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional string value = 2;
    public static final int VALUE_FIELD_NUMBER = 2;
    private java.lang.Object value_;
    public boolean hasValue() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public String getValue() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          value_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getValueBytes() {
      java.lang.Object ref = value_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        value_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      name_ = "";
      value_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getValueBytes());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getValueBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption)) {
        return super.equals(obj);
      }
      org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption other = (org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption) obj;
      
      boolean result = true;
      result = result && (hasName() == other.hasName());
      if (hasName()) {
        result = result && getName()
            .equals(other.getName());
      }
      result = result && (hasValue() == other.hasValue());
      if (hasValue()) {
        result = result && getValue()
            .equals(other.getValue());
      }
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasName()) {
        hash = (37 * hash) + NAME_FIELD_NUMBER;
        hash = (53 * hash) + getName().hashCode();
      }
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexOption_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexOption_fieldAccessorTable;
      }
      
      // Construct using org.apache.hadoop.hbase.index.protobuf.IndexOptionProtos.IndexOption.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        value_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.getDescriptor();
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption getDefaultInstanceForType() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.getDefaultInstance();
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption build() {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption buildPartial() {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption result = new org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.value_ = value_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption) {
          return mergeFrom((org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption other) {
        if (other == org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.getDefaultInstance()) return this;
        if (other.hasName()) {
          setName(other.getName());
        }
        if (other.hasValue()) {
          setValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              value_ = input.readBytes();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional string name = 1;
      private java.lang.Object name_ = "";
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setName(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      void setName(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
      }
      
      // optional string value = 2;
      private java.lang.Object value_ = "";
      public boolean hasValue() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public String getValue() {
        java.lang.Object ref = value_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          value_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setValue(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
        return this;
      }
      public Builder clearValue() {
        bitField0_ = (bitField0_ & ~0x00000002);
        value_ = getDefaultInstance().getValue();
        onChanged();
        return this;
      }
      void setValue(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000002;
        value_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:IndexOption)
    }
    
    static {
      defaultInstance = new IndexOption(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:IndexOption)
  }
  
  public interface IndexDefinitionOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional .IndexDefinition.Type type = 1;
    boolean hasType();
    org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type getType();
    
    // optional .IndexDefinition.Mode mode = 2;
    boolean hasMode();
    org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode getMode();
    
    // optional string data_interpretation = 3;
    boolean hasDataInterpretation();
    String getDataInterpretation();
    
    // optional bytes column_family = 4;
    boolean hasColumnFamily();
    com.google.protobuf.ByteString getColumnFamily();
    
    // optional bytes qualifer = 5;
    boolean hasQualifer();
    com.google.protobuf.ByteString getQualifer();
    
    // repeated .IndexOption option = 6;
    java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption> 
        getOptionList();
    org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption getOption(int index);
    int getOptionCount();
    java.util.List<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder> 
        getOptionOrBuilderList();
    org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder getOptionOrBuilder(
        int index);
  }
  public static final class IndexDefinition extends
      com.google.protobuf.GeneratedMessage
      implements IndexDefinitionOrBuilder {
    // Use IndexDefinition.newBuilder() to construct.
    private IndexDefinition(Builder builder) {
      super(builder);
    }
    private IndexDefinition(boolean noInit) {}
    
    private static final IndexDefinition defaultInstance;
    public static IndexDefinition getDefaultInstance() {
      return defaultInstance;
    }
    
    public IndexDefinition getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexDefinition_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexDefinition_fieldAccessorTable;
    }
    
    public enum Type
        implements com.google.protobuf.ProtocolMessageEnum {
      QUALIFIED_VALUE(0, 0),
      QUALIFIER_NAME(1, 1),
      ;
      
      public static final int QUALIFIED_VALUE_VALUE = 0;
      public static final int QUALIFIER_NAME_VALUE = 1;
      
      
      public final int getNumber() { return value; }
      
      public static Type valueOf(int value) {
        switch (value) {
          case 0: return QUALIFIED_VALUE;
          case 1: return QUALIFIER_NAME;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Type>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Type>() {
              public Type findValueByNumber(int number) {
                return Type.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.getDescriptor().getEnumTypes().get(0);
      }
      
      private static final Type[] VALUES = {
        QUALIFIED_VALUE, QUALIFIER_NAME, 
      };
      
      public static Type valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Type(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:IndexDefinition.Type)
    }
    
    public enum Mode
        implements com.google.protobuf.ProtocolMessageEnum {
      UNIQUE_INDEX(0, 0),
      SPARSE_INDEX(1, 1),
      DENSE_INDEX_ROW(2, 2),
      ;
      
      public static final int UNIQUE_INDEX_VALUE = 0;
      public static final int SPARSE_INDEX_VALUE = 1;
      public static final int DENSE_INDEX_ROW_VALUE = 2;
      
      
      public final int getNumber() { return value; }
      
      public static Mode valueOf(int value) {
        switch (value) {
          case 0: return UNIQUE_INDEX;
          case 1: return SPARSE_INDEX;
          case 2: return DENSE_INDEX_ROW;
          default: return null;
        }
      }
      
      public static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<Mode>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<Mode>() {
              public Mode findValueByNumber(int number) {
                return Mode.valueOf(number);
              }
            };
      
      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.getDescriptor().getEnumTypes().get(1);
      }
      
      private static final Mode[] VALUES = {
        UNIQUE_INDEX, SPARSE_INDEX, DENSE_INDEX_ROW, 
      };
      
      public static Mode valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }
      
      private final int index;
      private final int value;
      
      private Mode(int index, int value) {
        this.index = index;
        this.value = value;
      }
      
      // @@protoc_insertion_point(enum_scope:IndexDefinition.Mode)
    }
    
    private int bitField0_;
    // optional .IndexDefinition.Type type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type type_;
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type getType() {
      return type_;
    }
    
    // optional .IndexDefinition.Mode mode = 2;
    public static final int MODE_FIELD_NUMBER = 2;
    private org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode mode_;
    public boolean hasMode() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode getMode() {
      return mode_;
    }
    
    // optional string data_interpretation = 3;
    public static final int DATA_INTERPRETATION_FIELD_NUMBER = 3;
    private java.lang.Object dataInterpretation_;
    public boolean hasDataInterpretation() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public String getDataInterpretation() {
      java.lang.Object ref = dataInterpretation_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          dataInterpretation_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getDataInterpretationBytes() {
      java.lang.Object ref = dataInterpretation_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        dataInterpretation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    // optional bytes column_family = 4;
    public static final int COLUMN_FAMILY_FIELD_NUMBER = 4;
    private com.google.protobuf.ByteString columnFamily_;
    public boolean hasColumnFamily() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public com.google.protobuf.ByteString getColumnFamily() {
      return columnFamily_;
    }
    
    // optional bytes qualifer = 5;
    public static final int QUALIFER_FIELD_NUMBER = 5;
    private com.google.protobuf.ByteString qualifer_;
    public boolean hasQualifer() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public com.google.protobuf.ByteString getQualifer() {
      return qualifer_;
    }
    
    // repeated .IndexOption option = 6;
    public static final int OPTION_FIELD_NUMBER = 6;
    private java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption> option_;
    public java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption> getOptionList() {
      return option_;
    }
    public java.util.List<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder> 
        getOptionOrBuilderList() {
      return option_;
    }
    public int getOptionCount() {
      return option_.size();
    }
    public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption getOption(int index) {
      return option_.get(index);
    }
    public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder getOptionOrBuilder(
        int index) {
      return option_.get(index);
    }
    
    private void initFields() {
      type_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type.QUALIFIED_VALUE;
      mode_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode.UNIQUE_INDEX;
      dataInterpretation_ = "";
      columnFamily_ = com.google.protobuf.ByteString.EMPTY;
      qualifer_ = com.google.protobuf.ByteString.EMPTY;
      option_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getDataInterpretationBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, columnFamily_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, qualifer_);
      }
      for (int i = 0; i < option_.size(); i++) {
        output.writeMessage(6, option_.get(i));
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, mode_.getNumber());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getDataInterpretationBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, columnFamily_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, qualifer_);
      }
      for (int i = 0; i < option_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, option_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition)) {
        return super.equals(obj);
      }
      org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition other = (org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition) obj;
      
      boolean result = true;
      result = result && (hasType() == other.hasType());
      if (hasType()) {
        result = result &&
            (getType() == other.getType());
      }
      result = result && (hasMode() == other.hasMode());
      if (hasMode()) {
        result = result &&
            (getMode() == other.getMode());
      }
      result = result && (hasDataInterpretation() == other.hasDataInterpretation());
      if (hasDataInterpretation()) {
        result = result && getDataInterpretation()
            .equals(other.getDataInterpretation());
      }
      result = result && (hasColumnFamily() == other.hasColumnFamily());
      if (hasColumnFamily()) {
        result = result && getColumnFamily()
            .equals(other.getColumnFamily());
      }
      result = result && (hasQualifer() == other.hasQualifer());
      if (hasQualifer()) {
        result = result && getQualifer()
            .equals(other.getQualifer());
      }
      result = result && getOptionList()
          .equals(other.getOptionList());
      result = result &&
          getUnknownFields().equals(other.getUnknownFields());
      return result;
    }
    
    @java.lang.Override
    public int hashCode() {
      int hash = 41;
      hash = (19 * hash) + getDescriptorForType().hashCode();
      if (hasType()) {
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + hashEnum(getType());
      }
      if (hasMode()) {
        hash = (37 * hash) + MODE_FIELD_NUMBER;
        hash = (53 * hash) + hashEnum(getMode());
      }
      if (hasDataInterpretation()) {
        hash = (37 * hash) + DATA_INTERPRETATION_FIELD_NUMBER;
        hash = (53 * hash) + getDataInterpretation().hashCode();
      }
      if (hasColumnFamily()) {
        hash = (37 * hash) + COLUMN_FAMILY_FIELD_NUMBER;
        hash = (53 * hash) + getColumnFamily().hashCode();
      }
      if (hasQualifer()) {
        hash = (37 * hash) + QUALIFER_FIELD_NUMBER;
        hash = (53 * hash) + getQualifer().hashCode();
      }
      if (getOptionCount() > 0) {
        hash = (37 * hash) + OPTION_FIELD_NUMBER;
        hash = (53 * hash) + getOptionList().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      return hash;
    }
    
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinitionOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexDefinition_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.internal_static_IndexDefinition_fieldAccessorTable;
      }
      
      // Construct using org.apache.hadoop.hbase.index.protobuf.IndexOptionProtos.IndexDefinition.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getOptionFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        type_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type.QUALIFIED_VALUE;
        bitField0_ = (bitField0_ & ~0x00000001);
        mode_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode.UNIQUE_INDEX;
        bitField0_ = (bitField0_ & ~0x00000002);
        dataInterpretation_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        columnFamily_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000008);
        qualifer_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000010);
        if (optionBuilder_ == null) {
          option_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          optionBuilder_.clear();
        }
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.getDescriptor();
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition getDefaultInstanceForType() {
        return org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.getDefaultInstance();
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition build() {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition buildPartial() {
        org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition result = new org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.mode_ = mode_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.dataInterpretation_ = dataInterpretation_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.columnFamily_ = columnFamily_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.qualifer_ = qualifer_;
        if (optionBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            option_ = java.util.Collections.unmodifiableList(option_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.option_ = option_;
        } else {
          result.option_ = optionBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition) {
          return mergeFrom((org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition other) {
        if (other == org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasMode()) {
          setMode(other.getMode());
        }
        if (other.hasDataInterpretation()) {
          setDataInterpretation(other.getDataInterpretation());
        }
        if (other.hasColumnFamily()) {
          setColumnFamily(other.getColumnFamily());
        }
        if (other.hasQualifer()) {
          setQualifer(other.getQualifer());
        }
        if (optionBuilder_ == null) {
          if (!other.option_.isEmpty()) {
            if (option_.isEmpty()) {
              option_ = other.option_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureOptionIsMutable();
              option_.addAll(other.option_);
            }
            onChanged();
          }
        } else {
          if (!other.option_.isEmpty()) {
            if (optionBuilder_.isEmpty()) {
              optionBuilder_.dispose();
              optionBuilder_ = null;
              option_ = other.option_;
              bitField0_ = (bitField0_ & ~0x00000020);
              optionBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getOptionFieldBuilder() : null;
            } else {
              optionBuilder_.addAllMessages(other.option_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type value = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode value = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                mode_ = value;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              dataInterpretation_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              columnFamily_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              qualifer_ = input.readBytes();
              break;
            }
            case 50: {
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder subBuilder = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addOption(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional .IndexDefinition.Type type = 1;
      private org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type type_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type.QUALIFIED_VALUE;
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type getType() {
        return type_;
      }
      public Builder setType(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Type.QUALIFIED_VALUE;
        onChanged();
        return this;
      }
      
      // optional .IndexDefinition.Mode mode = 2;
      private org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode mode_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode.UNIQUE_INDEX;
      public boolean hasMode() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode getMode() {
        return mode_;
      }
      public Builder setMode(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        mode_ = value;
        onChanged();
        return this;
      }
      public Builder clearMode() {
        bitField0_ = (bitField0_ & ~0x00000002);
        mode_ = org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Mode.UNIQUE_INDEX;
        onChanged();
        return this;
      }
      
      // optional string data_interpretation = 3;
      private java.lang.Object dataInterpretation_ = "";
      public boolean hasDataInterpretation() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public String getDataInterpretation() {
        java.lang.Object ref = dataInterpretation_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          dataInterpretation_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setDataInterpretation(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        dataInterpretation_ = value;
        onChanged();
        return this;
      }
      public Builder clearDataInterpretation() {
        bitField0_ = (bitField0_ & ~0x00000004);
        dataInterpretation_ = getDefaultInstance().getDataInterpretation();
        onChanged();
        return this;
      }
      void setDataInterpretation(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000004;
        dataInterpretation_ = value;
        onChanged();
      }
      
      // optional bytes column_family = 4;
      private com.google.protobuf.ByteString columnFamily_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasColumnFamily() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public com.google.protobuf.ByteString getColumnFamily() {
        return columnFamily_;
      }
      public Builder setColumnFamily(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        columnFamily_ = value;
        onChanged();
        return this;
      }
      public Builder clearColumnFamily() {
        bitField0_ = (bitField0_ & ~0x00000008);
        columnFamily_ = getDefaultInstance().getColumnFamily();
        onChanged();
        return this;
      }
      
      // optional bytes qualifer = 5;
      private com.google.protobuf.ByteString qualifer_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasQualifer() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public com.google.protobuf.ByteString getQualifer() {
        return qualifer_;
      }
      public Builder setQualifer(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        qualifer_ = value;
        onChanged();
        return this;
      }
      public Builder clearQualifer() {
        bitField0_ = (bitField0_ & ~0x00000010);
        qualifer_ = getDefaultInstance().getQualifer();
        onChanged();
        return this;
      }
      
      // repeated .IndexOption option = 6;
      private java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption> option_ =
        java.util.Collections.emptyList();
      private void ensureOptionIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          option_ = new java.util.ArrayList<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption>(option_);
          bitField0_ |= 0x00000020;
         }
      }
      
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder> optionBuilder_;
      
      public java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption> getOptionList() {
        if (optionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(option_);
        } else {
          return optionBuilder_.getMessageList();
        }
      }
      public int getOptionCount() {
        if (optionBuilder_ == null) {
          return option_.size();
        } else {
          return optionBuilder_.getCount();
        }
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption getOption(int index) {
        if (optionBuilder_ == null) {
          return option_.get(index);
        } else {
          return optionBuilder_.getMessage(index);
        }
      }
      public Builder setOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption value) {
        if (optionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOptionIsMutable();
          option_.set(index, value);
          onChanged();
        } else {
          optionBuilder_.setMessage(index, value);
        }
        return this;
      }
      public Builder setOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder builderForValue) {
        if (optionBuilder_ == null) {
          ensureOptionIsMutable();
          option_.set(index, builderForValue.build());
          onChanged();
        } else {
          optionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addOption(org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption value) {
        if (optionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOptionIsMutable();
          option_.add(value);
          onChanged();
        } else {
          optionBuilder_.addMessage(value);
        }
        return this;
      }
      public Builder addOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption value) {
        if (optionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureOptionIsMutable();
          option_.add(index, value);
          onChanged();
        } else {
          optionBuilder_.addMessage(index, value);
        }
        return this;
      }
      public Builder addOption(
          org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder builderForValue) {
        if (optionBuilder_ == null) {
          ensureOptionIsMutable();
          option_.add(builderForValue.build());
          onChanged();
        } else {
          optionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      public Builder addOption(
          int index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder builderForValue) {
        if (optionBuilder_ == null) {
          ensureOptionIsMutable();
          option_.add(index, builderForValue.build());
          onChanged();
        } else {
          optionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      public Builder addAllOption(
          java.lang.Iterable<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption> values) {
        if (optionBuilder_ == null) {
          ensureOptionIsMutable();
          super.addAll(values, option_);
          onChanged();
        } else {
          optionBuilder_.addAllMessages(values);
        }
        return this;
      }
      public Builder clearOption() {
        if (optionBuilder_ == null) {
          option_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          optionBuilder_.clear();
        }
        return this;
      }
      public Builder removeOption(int index) {
        if (optionBuilder_ == null) {
          ensureOptionIsMutable();
          option_.remove(index);
          onChanged();
        } else {
          optionBuilder_.remove(index);
        }
        return this;
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder getOptionBuilder(
          int index) {
        return getOptionFieldBuilder().getBuilder(index);
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder getOptionOrBuilder(
          int index) {
        if (optionBuilder_ == null) {
          return option_.get(index);  } else {
          return optionBuilder_.getMessageOrBuilder(index);
        }
      }
      public java.util.List<? extends org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder> 
           getOptionOrBuilderList() {
        if (optionBuilder_ != null) {
          return optionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(option_);
        }
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder addOptionBuilder() {
        return getOptionFieldBuilder().addBuilder(
            org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.getDefaultInstance());
      }
      public org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder addOptionBuilder(
          int index) {
        return getOptionFieldBuilder().addBuilder(
            index, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.getDefaultInstance());
      }
      public java.util.List<org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder> 
           getOptionBuilderList() {
        return getOptionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder> 
          getOptionFieldBuilder() {
        if (optionBuilder_ == null) {
          optionBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder, org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOptionOrBuilder>(
                  option_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          option_ = null;
        }
        return optionBuilder_;
      }
      
      // @@protoc_insertion_point(builder_scope:IndexDefinition)
    }
    
    static {
      defaultInstance = new IndexDefinition(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:IndexDefinition)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_TableIndexOptions_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_TableIndexOptions_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexOption_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IndexOption_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_IndexDefinition_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_IndexDefinition_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n$src/main/protobuf/IndexOptions.proto\";" +
      "\n\021TableIndexOptions\022&\n\014index_option\030\001 \003(" +
      "\0132\020.IndexDefinition\"*\n\013IndexOption\022\014\n\004na" +
      "me\030\001 \001(\t\022\r\n\005value\030\002 \001(\t\"\261\002\n\017IndexDefinit" +
      "ion\022#\n\004type\030\001 \001(\0162\025.IndexDefinition.Type" +
      "\022#\n\004mode\030\002 \001(\0162\025.IndexDefinition.Mode\022\033\n" +
      "\023data_interpretation\030\003 \001(\t\022\025\n\rcolumn_fam" +
      "ily\030\004 \001(\014\022\020\n\010qualifer\030\005 \001(\014\022\034\n\006option\030\006 " +
      "\003(\0132\014.IndexOption\"/\n\004Type\022\023\n\017QUALIFIED_V" +
      "ALUE\020\000\022\022\n\016QUALIFIER_NAME\020\001\"?\n\004Mode\022\020\n\014UN",
      "IQUE_INDEX\020\000\022\020\n\014SPARSE_INDEX\020\001\022\023\n\017DENSE_" +
      "INDEX_ROW\020\002BC\n&org.apache.hadoop.hbase.i" +
      "ndex.protobufB\021IndexOptionProtosH\001\210\001\001\240\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_TableIndexOptions_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_TableIndexOptions_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_TableIndexOptions_descriptor,
              new java.lang.String[] { "IndexOption", },
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions.class,
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.TableIndexOptions.Builder.class);
          internal_static_IndexOption_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_IndexOption_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IndexOption_descriptor,
              new java.lang.String[] { "Name", "Value", },
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.class,
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexOption.Builder.class);
          internal_static_IndexDefinition_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_IndexDefinition_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_IndexDefinition_descriptor,
              new java.lang.String[] { "Type", "Mode", "DataInterpretation", "ColumnFamily", "Qualifer", "Option", },
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.class,
              org.apache.hadoop.hbase.index.common.protobuf.IndexOptionProtos.IndexDefinition.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
